# fly.toml app configuration file generated for node-autumn-leaf-1967 on 2025-04-26T20:51:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'node-dark-morning-7683'
primary_region = 'sin'

[build]
  # No custom builder specified, Fly.io will use the default behavior

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
